import { CountryNode } from './countryNodeTypes';

export const INITIAL_COUNTRY_NODES: CountryNode[] = [
  {
    countryNodeId: 'CN-PAK',
    countryCode: 'PAK',
    countryName: 'Pakistan',
    region: 'South Asia',
    currency: 'PKR',
    timezone: 'Asia/Karachi',
    regulatoryProfile: 'State Bank of Pakistan (SBP) / SECP Shariah Board',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-08-04T16:00:00Z',
    activeOrganisationsCount: 22,
    activeUsersCount: 165,
    activeProjectsCount: 28,
    activePoolsCount: 10,
    flagUrl: 'https://flagcdn.com/w80/pk.png'
  },
  {
    countryNodeId: 'CN-MYS',
    countryCode: 'MYS',
    countryName: 'Malaysia',
    region: 'Southeast Asia',
    currency: 'MYR',
    timezone: 'Asia/Kuala_Lumpur',
    regulatoryProfile: 'Bank Negara Malaysia / Securities Commission Malaysia (SCM)',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
    activeOrganisationsCount: 18,
    activeUsersCount: 142,
    activeProjectsCount: 24,
    activePoolsCount: 8,
    flagUrl: 'https://flagcdn.com/w80/my.png'
  },
  {
    countryNodeId: 'CN-EGY',
    countryCode: 'EGY',
    countryName: 'Egypt',
    region: 'North Africa',
    currency: 'EGP',
    timezone: 'Africa/Cairo',
    regulatoryProfile: 'Central Bank of Egypt (CBE) / Financial Regulatory Authority (FRA)',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-08-05T10:00:00Z',
    activeOrganisationsCount: 15,
    activeUsersCount: 98,
    activeProjectsCount: 16,
    activePoolsCount: 6,
    flagUrl: 'https://flagcdn.com/w80/eg.png'
  },
  {
    countryNodeId: 'CN-IDN',
    countryCode: 'IDN',
    countryName: 'Indonesia',
    region: 'Southeast Asia',
    currency: 'IDR',
    timezone: 'Asia/Jakarta',
    regulatoryProfile: 'Otoritas Jasa Keuangan (OJK) / Bank Indonesia / DSN-MUI',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2026-08-02T14:30:00Z',
    activeOrganisationsCount: 12,
    activeUsersCount: 85,
    activeProjectsCount: 14,
    activePoolsCount: 5,
    flagUrl: 'https://flagcdn.com/w80/id.png'
  },
  {
    countryNodeId: 'CN-TUR',
    countryCode: 'TUR',
    countryName: 'Türkiye',
    region: 'Eurasia',
    currency: 'TRY',
    timezone: 'Europe/Istanbul',
    regulatoryProfile: 'Banking Regulation and Supervision Agency (BDDK) / CMB',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-05-20T00:00:00Z',
    updatedAt: '2026-07-28T11:15:00Z',
    activeOrganisationsCount: 9,
    activeUsersCount: 64,
    activeProjectsCount: 10,
    activePoolsCount: 4,
    flagUrl: 'https://flagcdn.com/w80/tr.png'
  },
  {
    countryNodeId: 'CN-NGA',
    countryCode: 'NGA',
    countryName: 'Nigeria',
    region: 'West Africa',
    currency: 'NGN',
    timezone: 'Africa/Lagos',
    regulatoryProfile: 'Central Bank of Nigeria (CBN) / Securities & Exchange Commission (SEC)',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-08-10T00:00:00Z',
    updatedAt: '2026-08-08T09:00:00Z',
    activeOrganisationsCount: 7,
    activeUsersCount: 42,
    activeProjectsCount: 8,
    activePoolsCount: 3,
    flagUrl: 'https://flagcdn.com/w80/ng.png'
  },
  {
    countryNodeId: 'CN-BGD',
    countryCode: 'BGD',
    countryName: 'Bangladesh',
    region: 'South Asia',
    currency: 'BDT',
    timezone: 'Asia/Dhaka',
    regulatoryProfile: 'Bangladesh Bank (BB) / Bangladesh Securities and Exchange Commission (BSEC)',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
    activeOrganisationsCount: 8,
    activeUsersCount: 46,
    activeProjectsCount: 9,
    activePoolsCount: 3,
    flagUrl: 'https://flagcdn.com/w80/bd.png'
  },
  {
    countryNodeId: 'CN-IRN',
    countryCode: 'IRN',
    countryName: 'Iran',
    region: 'Middle East',
    currency: 'IRR',
    timezone: 'Asia/Tehran',
    regulatoryProfile: 'Central Bank of the Islamic Republic of Iran (CBI) / SEO',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2026-08-12T14:00:00Z',
    activeOrganisationsCount: 6,
    activeUsersCount: 38,
    activeProjectsCount: 7,
    activePoolsCount: 2,
    flagUrl: 'https://flagcdn.com/w80/ir.png'
  }
];
