import React, { useState } from 'react';
import { Download, FileSpreadsheet, FileText } from 'lucide-react';
import { StatementFormat, statementsApi } from '../../services/statementsApi';

const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Kuala_Lumpur' });

/**
 * Investor statement download, generated by the server from the ledger for the chosen
 * period (dates in the user's country time). Replaces the old mock archive list.
 */
export const StatementsPanel: React.FC = () => {
  const [from, setFrom] = useState(`${today().slice(0, 4)}-01-01`);
  const [to, setTo] = useState(today());
  const [busy, setBusy] = useState<StatementFormat | null>(null);
  const [error, setError] = useState('');

  const download = async (format: StatementFormat) => {
    setBusy(format);
    setError('');
    try {
      await statementsApi.downloadInvestorStatement({ from, to, format });
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'The statement could not be generated.');
    } finally {
      setBusy(null);
    }
  };

  const presets: Array<[string, () => [string, string]]> = [
    ['Year to date', () => [`${today().slice(0, 4)}-01-01`, today()]],
    ['Last year', () => { const year = Number(today().slice(0, 4)) - 1; return [`${year}-01-01`, `${year}-12-31`]; }],
  ];

  return (
    <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200/80 dark:border-slate-700/80 p-6 shadow-sm space-y-4">
      <div>
        <h3 className="text-lg font-black text-slate-900 dark:text-white">Investor Statement</h3>
        <p className="text-xs text-slate-500 mt-1">Holdings, investment orders with the akad you accepted, and profit distributions for the period, generated from the platform ledger.</p>
      </div>
      <div className="flex flex-wrap items-end gap-3 text-xs">
        <label className="space-y-1"><span className="block font-bold text-slate-600 dark:text-slate-300">From</span><input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} className="p-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white" /></label>
        <label className="space-y-1"><span className="block font-bold text-slate-600 dark:text-slate-300">To</span><input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} className="p-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white" /></label>
        {presets.map(([label, range]) => <button key={label} type="button" onClick={() => { const [start, end] = range(); setFrom(start); setTo(end); }} className="px-3 py-2 rounded-lg bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-200 font-bold">{label}</button>)}
      </div>
      <div className="flex flex-wrap gap-2">
        <button onClick={() => void download('pdf')} disabled={busy !== null || !from || !to} className="px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold flex items-center gap-2 disabled:opacity-50"><FileText className="w-4 h-4" /> {busy === 'pdf' ? 'Generating…' : 'Download PDF'}</button>
        <button onClick={() => void download('csv')} disabled={busy !== null || !from || !to} className="px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-black dark:bg-slate-700 text-white text-xs font-bold flex items-center gap-2 disabled:opacity-50"><FileSpreadsheet className="w-4 h-4" /> {busy === 'csv' ? 'Generating…' : 'Download CSV'}</button>
      </div>
      {error && <div className="p-3 rounded-xl bg-rose-50 dark:bg-rose-950/30 text-xs font-semibold text-rose-700 dark:text-rose-300">{error}</div>}
      <p className="text-[11px] text-slate-400 flex items-start gap-1.5"><Download className="w-3.5 h-3.5 shrink-0 mt-0.5" /> This statement is not a tax or zakat assessment. Returns are not guaranteed.</p>
    </div>
  );
};
