import { authService } from '../auth/services/authService';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || `http://${window.location.hostname}:3001`;

export type StatementFormat = 'pdf' | 'csv';

/** Downloads a statement generated by the server from the ledger (GET /statements/...). */
async function download(path: string, query: { from?: string; to?: string; format: StatementFormat }) {
  const params = new URLSearchParams({ format: query.format });
  if (query.from) params.set('from', query.from);
  if (query.to) params.set('to', query.to);
  const token = authService.getAuthState().session?.token;
  const response = await fetch(`${API_BASE_URL}${path}?${params}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} });
  if (!response.ok) {
    const body = await response.json().catch(() => null) as { message?: string | string[] } | null;
    throw new Error((Array.isArray(body?.message) ? body?.message.join(' ') : body?.message) || 'The statement could not be generated.');
  }
  const blobUrl = URL.createObjectURL(await response.blob());
  const link = document.createElement('a');
  link.href = blobUrl;
  link.download = response.headers.get('content-disposition')?.match(/filename="?([^";]+)"?/i)?.[1] || `statement.${query.format}`;
  link.click();
  URL.revokeObjectURL(blobUrl);
}

export const statementsApi = {
  downloadInvestorStatement: (query: { from?: string; to?: string; format: StatementFormat }) => download('/statements/investor', query),
  downloadProjectStatement: (projectId: string, query: { from?: string; to?: string; format: StatementFormat }) => download(`/statements/projects/${encodeURIComponent(projectId)}`, query),
};
