import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { AuditService } from '../audit/audit.service';
import { AuthenticatedUser } from '../auth/identity.service';
import { PolicyService } from '../policy/policy.service';
import { PrismaService } from '../prisma.service';
import { assertTenantScope, tenantScopeFilter } from '../tenancy/tenant-scope';
import { CreateContractClauseDto, CreateContractInputSchemaDto, CreateContractTemplateDto, CreateDocumentVersionDto, CreateShariahRuleDto } from './contract-intelligence.dto';

@Injectable()
export class ContractIntelligenceService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly policy: PolicyService) {}

  async listTemplates(actor: AuthenticatedUser, contractType?: string) { this.require(actor, 'read'); return this.prisma.contractTemplate.findMany({ where: { ...tenantScopeFilter(actor), ...(contractType ? { contractType } : {}) }, include: { clauses: { where: { approvalStatus: 'APPROVED' } } }, orderBy: [{ contractType: 'asc' }, { templateName: 'asc' }, { version: 'desc' }] }); }
  async createTemplate(input: CreateContractTemplateDto, actor: AuthenticatedUser) { this.require(actor, 'create'); const record = await this.prisma.contractTemplate.create({ data: { ...this.scope(actor), ...input, version: input.version || 1, status: input.status || 'ACTIVE', approvalStatus: input.approvalStatus || 'PENDING', createdBy: actor.userId } }); await this.auditRecord(actor, 'contract_intelligence.template_created', record.id, { contractType: record.contractType, templateName: record.templateName }); return record; }

  async listClauses(actor: AuthenticatedUser, contractType?: string) { this.require(actor, 'read'); return this.prisma.contractClause.findMany({ where: { ...tenantScopeFilter(actor), approvalStatus: 'APPROVED', ...(contractType ? { contractType } : {}) }, orderBy: [{ contractType: 'asc' }, { clauseCategory: 'asc' }, { clauseTitle: 'asc' }] }); }
  async createClause(input: CreateContractClauseDto, actor: AuthenticatedUser) { this.require(actor, 'create'); if (input.templateId) { const template = await this.prisma.contractTemplate.findFirst({ where: { id: input.templateId, ...tenantScopeFilter(actor) } }); if (!template) throw new NotFoundException('Contract template not found'); } const record = await this.prisma.contractClause.create({ data: { ...this.scope(actor), ...input, riskLevel: input.riskLevel || 'MEDIUM', approvalStatus: input.approvalStatus || 'PENDING', createdBy: actor.userId } }); await this.auditRecord(actor, 'contract_intelligence.clause_created', record.id, { contractType: record.contractType, clauseTitle: record.clauseTitle }); return record; }

  async listInputSchemas(actor: AuthenticatedUser, contractType?: string) { this.require(actor, 'read'); return this.prisma.contractInputSchema.findMany({ where: { ...tenantScopeFilter(actor), approvalStatus: 'APPROVED', ...(contractType ? { contractType } : {}) }, orderBy: [{ contractType: 'asc' }, { version: 'desc' }] }); }
  async createInputSchema(input: CreateContractInputSchemaDto, actor: AuthenticatedUser) { this.require(actor, 'create'); const record = await this.prisma.contractInputSchema.create({ data: { ...this.scope(actor), contractType: input.contractType, schemaName: input.schemaName, requiredFields: input.requiredFields, version: input.version || 1, status: input.status || 'ACTIVE', approvalStatus: input.approvalStatus || 'PENDING', createdBy: actor.userId } }); await this.auditRecord(actor, 'contract_intelligence.input_schema_created', record.id, { contractType: record.contractType, schemaName: record.schemaName }); return record; }

  async listRules(actor: AuthenticatedUser, contractType?: string, jurisdiction?: string) { this.require(actor, 'read'); return this.prisma.shariahRule.findMany({ where: { ...tenantScopeFilter(actor), approvalStatus: 'APPROVED', ...(contractType ? { contractType } : {}), ...(jurisdiction ? { OR: [{ jurisdiction }, { jurisdiction: null }, { jurisdiction: 'International' }] } : {}) }, orderBy: [{ contractType: 'asc' }, { severity: 'desc' }, { ruleName: 'asc' }] }); }
  async createRule(input: CreateShariahRuleDto, actor: AuthenticatedUser) { this.require(actor, 'create'); const record = await this.prisma.shariahRule.create({ data: { ...this.scope(actor), ...input, severity: input.severity || 'MEDIUM', approvalStatus: input.approvalStatus || 'PENDING', createdBy: actor.userId } }); await this.auditRecord(actor, 'contract_intelligence.rule_created', record.id, { contractType: record.contractType, ruleName: record.ruleName }); return record; }

  async listDocumentVersions(documentId: string, actor: AuthenticatedUser) { this.require(actor, 'read'); const document = await this.getContract(documentId, actor); return this.prisma.documentVersion.findMany({ where: { documentId: document.id, ...tenantScopeFilter(actor) }, orderBy: { version: 'desc' } }); }
  async createDocumentVersion(documentId: string, input: CreateDocumentVersionDto, actor: AuthenticatedUser) { this.require(actor, 'update'); const document = await this.getContract(documentId, actor); const latest = await this.prisma.documentVersion.findFirst({ where: { documentId, ...tenantScopeFilter(actor) }, orderBy: { version: 'desc' } }); const record = await this.prisma.documentVersion.create({ data: { documentId, ...this.scope(actor), version: (latest?.version || 0) + 1, createdBy: actor.userId, reviewStatus: input.reviewStatus || 'DRAFT' } }); await this.auditRecord(actor, 'contract_intelligence.document_version_created', record.id, { documentId: document.id, version: record.version, reviewStatus: record.reviewStatus }); return record; }

  private async getContract(id: string, actor: AuthenticatedUser) { const contract = await this.prisma.contract.findUnique({ where: { id } }); if (!contract) throw new NotFoundException('Contract document not found'); assertTenantScope(actor, contract, 'Contract document'); return contract; }
  private scope(actor: AuthenticatedUser) { return { organisationId: actor.organisationId, countryNodeId: actor.countryNodeId }; }
  private require(actor: AuthenticatedUser, action: 'read' | 'create' | 'update') { if (!this.policy.can(actor.role, 'contracts', action)) throw new ForbiddenException(this.policy.evaluate(actor.role, 'contracts', action).reason); }
  private async auditRecord(actor: AuthenticatedUser, action: string, resourceId: string, metadata: Record<string, unknown>) { await this.audit.recordActor(actor, { action, resourceType: 'ContractIntelligence', resourceId, organisationId: actor.organisationId, countryNodeId: actor.countryNodeId, metadata }); }
}
