import { AuthUser } from '../types/authTypes';

export const DEMO_PERSONAS: Record<string, AuthUser> = {
  'Super Admin': {
    userId: 'USR-SYS-001',
    name: 'Dr. Tariq Al-Mansoor',
    email: 'superadmin@how.org',
    organisationId: 'ORG-D8-GOV',
    organisationName: 'D-8 Central Treasury Board',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Super Admin', 'Security Administrator', 'Country Admin'],
    activeRole: 'Super Admin',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
  },
  'Country Admin': {
    userId: 'USR-MYS-P2-001',
    name: 'Ahmed Al-Mansoor',
    email: 'ahmed.almansoor@how.org',
    organisationId: 'ORG-MYS-P2-CAP',
    organisationName: 'Malaysian Sovereign Capital Assets',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Country Admin', 'Project Sponsor', 'Finance Officer'],
    activeRole: 'Country Admin',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
  },
  'Organization Admin': {
    userId: 'USR-ORG-002',
    name: 'Sultan Mahmud',
    email: 'orgadmin@mycapital.my',
    organisationId: 'ORG-MYS-P2-CAP',
    organisationName: 'Malaysian Sovereign Capital Assets',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Organization Admin', 'Project Sponsor'],
    activeRole: 'Organization Admin',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
  },
  'Project Sponsor': {
    userId: 'USR-TUR-003',
    name: 'Emin Yilmaz',
    email: 'emin.sponsor@istanbultech.tr',
    organisationId: 'ORG-BORS-IST',
    organisationName: 'Istanbul Tech Park & Energy',
    countryNodeId: 'CN-TUR',
    countryName: 'Turkey Node',
    assignedRoles: ['Project Sponsor', 'Project Manager'],
    activeRole: 'Project Sponsor',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80'
  },
  'Project Manager': {
    userId: 'USR-PM-004',
    name: 'Zeynep Kaya',
    email: 'zeynep.pm@istanbultech.tr',
    organisationId: 'ORG-BORS-IST',
    organisationName: 'Istanbul Tech Park & Energy',
    countryNodeId: 'CN-TUR',
    countryName: 'Turkey Node',
    assignedRoles: ['Project Manager'],
    activeRole: 'Project Manager',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80'
  },
  'Asset Owner': {
    userId: 'USR-AO-005',
    name: 'Rashid Al-Nuaimi',
    email: 'rashid.assets@mycapital.my',
    organisationId: 'ORG-MYS-P2-CAP',
    organisationName: 'Malaysian Sovereign Capital Assets',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Asset Owner'],
    activeRole: 'Asset Owner',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80'
  },
  'Pool Manager': {
    userId: 'USR-POOL-006',
    name: 'Faisal Basri',
    email: 'faisal.pools@nusacapital.co.id',
    organisationId: 'ORG-NUSA-DEV',
    organisationName: 'Nusa Capital Management',
    countryNodeId: 'CN-IDN',
    countryName: 'Indonesia Node',
    assignedRoles: ['Pool Manager', 'Finance Officer'],
    activeRole: 'Pool Manager',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80'
  },
  'Retail Investor': {
    userId: 'USR-INV-007',
    name: 'Nurul Huda',
    email: 'nurul.investor@gmail.com',
    organisationId: 'ORG-NUSA-DEV',
    organisationName: 'Nusa Capital Retail Pool',
    countryNodeId: 'CN-IDN',
    countryName: 'Indonesia Node',
    assignedRoles: ['Retail Investor'],
    activeRole: 'Retail Investor',
    status: 'ACTIVE',
    mfaStatus: 'Disabled',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80'
  },
  'Institutional Investor': {
    userId: 'USR-INST-008',
    name: 'Khaled bin Sulaiman',
    email: 'khaled.allocations@d8fund.org',
    organisationId: 'ORG-D8-GOV',
    organisationName: 'D-8 Sovereign Investment Board',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Institutional Investor'],
    activeRole: 'Institutional Investor',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80'
  },
  'Shariah Advisor': {
    userId: 'USR-MYS-002',
    name: 'Tengku Dr. Hasmadi',
    email: 'hasmadi@shariahboard.d8.org',
    organisationId: 'ORG-D8-GOV',
    organisationName: 'AAOIFI Shariah Governance Board',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Shariah Advisor', 'Shariah Reviewer'],
    activeRole: 'Shariah Advisor',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80'
  },
  'Compliance Officer': {
    userId: 'USR-IDN-004',
    name: 'Nurul Hidayah',
    email: 'nurul.compliance@how.org',
    organisationId: 'ORG-NUSA-DEV',
    organisationName: 'Nusa Capital Management',
    countryNodeId: 'CN-IDN',
    countryName: 'Indonesia Node',
    assignedRoles: ['Compliance Officer', 'Legal Officer'],
    activeRole: 'Compliance Officer',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80'
  },
  'Risk Officer': {
    userId: 'USR-RISK-010',
    name: 'Farhan Rahman',
    email: 'farhan.risk@silkroadagro.bd',
    organisationId: 'ORG-SILK-TEX',
    organisationName: 'Chittagong Silk & Agro',
    countryNodeId: 'CN-BGD',
    countryName: 'Bangladesh Node',
    assignedRoles: ['Risk Officer'],
    activeRole: 'Risk Officer',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80'
  },
  'Finance Officer': {
    userId: 'USR-EGY-005',
    name: 'Dr. Tariq Al-Hashimi',
    email: 'tariq.finance@how.org',
    organisationId: 'ORG-MYS-P2-CAP',
    organisationName: 'Gulf Capital Assets',
    countryNodeId: 'CN-EGY',
    countryName: 'Egypt Node',
    assignedRoles: ['Finance Officer', 'Treasury Officer'],
    activeRole: 'Finance Officer',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
  },
  'Auditor': {
    userId: 'USR-AUD-012',
    name: 'Khadija El-Sayed',
    email: 'khadija.audit@pwc-d8.org',
    organisationId: 'ORG-D8-GOV',
    organisationName: 'D-8 External Audit Panel',
    countryNodeId: 'CN-EGY',
    countryName: 'Egypt Node',
    assignedRoles: ['Auditor'],
    activeRole: 'Auditor',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80'
  },
  'Customer Support': {
    userId: 'USR-SUPP-013',
    name: 'Amir Hoseini',
    email: 'support.lead@how.org',
    organisationId: 'ORG-MYS-P2-CAP',
    organisationName: 'House of Wealth Support Hub',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Customer Support'],
    activeRole: 'Customer Support',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
  },
  'AI Model Reviewer': {
    userId: 'USR-AI-014',
    name: 'Prof. Dr. Hassan Al-Bakri',
    email: 'ai.governance@how.org',
    organisationId: 'ORG-D8-GOV',
    organisationName: 'D-8 AI & Algorithmic Ethics Council',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['AI Model Reviewer'],
    activeRole: 'AI Model Reviewer',
    status: 'ACTIVE',
    mfaStatus: 'Enforced',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80'
  },
  'Guest': {
    userId: 'GUEST-001',
    name: 'Guest Visitor',
    email: 'visitor@public-d8.org',
    organisationId: 'ORG-PUBLIC',
    organisationName: 'House of Wealth Public Portal',
    countryNodeId: 'CN-MYS',
    countryName: 'Malaysia Node',
    assignedRoles: ['Guest'],
    activeRole: 'Guest',
    status: 'ACTIVE',
    mfaStatus: 'Enabled',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80'
  }
};
