import { AppUser } from './userTypes';

export const INITIAL_APP_USERS: AppUser[] = [
  {
    userId: 'USR-MYS-001',
    fullName: 'Ahmad bin Razak',
    email: 'ahmad.razak@felda.gov.my',
    phone: '+60 12 998 1122',
    department: 'Agricultural Development Projects',
    jobTitle: 'Senior PDP & Project Sponsor Lead',
    organisationId: 'ORG-FELDA-MYS',
    countryNodeId: 'CN-MYS',
    status: 'ACTIVE',
    primaryRole: 'Project Sponsor',
    assignedRoles: ['Project Sponsor', 'Project Manager'],
    mfaEnabled: true,
    mfaStatus: 'Enforced',
    kycLevel: 'Corporate KYB',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-11T16:30:00Z',
    joinedDate: 'Jan 2024',
    timezone: 'Asia/Kuala_Lumpur',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2026-08-11T16:30:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01',
    roleHistory: [
      {
        id: 'RH-001',
        userId: 'USR-MYS-001',
        organisationId: 'ORG-FELDA-MYS',
        performedBy: 'FELDA Org Admin',
        oldRole: 'Project Manager',
        newRole: 'Project Sponsor',
        timestamp: '2025-01-15T10:00:00Z',
        reason: 'Promotion to Chief Project Sponsor for Smart Agritech Sukuk',
        status: 'Completed'
      }
    ]
  },
  {
    userId: 'USR-MYS-002',
    fullName: 'Siti Aminah',
    email: 'siti.aminah@felda.gov.my',
    phone: '+60 13 445 7788',
    department: 'Finance & Sukuk Treasury',
    jobTitle: 'Head of Treasury & Financial Controls',
    organisationId: 'ORG-FELDA-MYS',
    countryNodeId: 'CN-MYS',
    status: 'ACTIVE',
    primaryRole: 'Finance Officer',
    assignedRoles: ['Finance Officer', 'Project Sponsor'],
    mfaEnabled: true,
    mfaStatus: 'Enforced',
    kycLevel: 'Level 3',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-11T14:15:00Z',
    joinedDate: 'Mar 2024',
    timezone: 'Asia/Kuala_Lumpur',
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2026-08-11T14:15:00Z',
    createdBy: 'USR-MYS-001',
    updatedBy: 'USR-MYS-001',
    roleHistory: []
  },
  {
    userId: 'USR-MYS-003',
    fullName: 'Ali Hassan',
    email: 'ali.hassan@felda.gov.my',
    phone: '+60 17 332 9900',
    department: 'Estate Operations',
    jobTitle: 'Site Operations Project Manager',
    organisationId: 'ORG-FELDA-MYS',
    countryNodeId: 'CN-MYS',
    status: 'PENDING',
    primaryRole: 'Project Manager',
    assignedRoles: ['Project Manager'],
    mfaEnabled: false,
    mfaStatus: 'Disabled',
    kycLevel: 'Level 1',
    verified: false,
    profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    lastLogin: 'Never',
    joinedDate: 'Aug 2026',
    timezone: 'Asia/Kuala_Lumpur',
    createdAt: '2026-08-08T11:00:00Z',
    updatedAt: '2026-08-08T11:00:00Z',
    createdBy: 'USR-MYS-001',
    updatedBy: 'USR-MYS-001',
    roleHistory: []
  },
  {
    userId: 'USR-MYS-004',
    fullName: 'Tengku Dr. Hasmadi',
    email: 'hasmadi@shariahboard.d8.org',
    phone: '+60 12 345 6789',
    department: 'AAOIFI Shariah Governance Board',
    jobTitle: 'Chairman of Shariah Supervisory Council',
    organisationId: 'ORG-D8-GOV',
    countryNodeId: 'CN-MYS',
    status: 'ACTIVE',
    primaryRole: 'Shariah Advisor',
    assignedRoles: ['Shariah Advisor', 'Shariah Reviewer'],
    mfaEnabled: true,
    mfaStatus: 'Enforced',
    kycLevel: 'Level 3',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-11T12:00:00Z',
    joinedDate: 'Mar 2024',
    timezone: 'Asia/Kuala_Lumpur',
    createdAt: '2024-03-15T09:00:00Z',
    updatedAt: '2026-08-11T12:00:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01',
    roleHistory: []
  },
  {
    userId: 'USR-PAK-001',
    fullName: 'Ahmed Al-Mansoor',
    email: 'ahmed.almansoor@pakcapital.pk',
    phone: '+92 51 123 4567',
    department: 'Asset Tokenization & Treasury',
    jobTitle: 'Managing Director & Country Admin',
    organisationId: 'ORG-GULF-CAP',
    countryNodeId: 'CN-PAK',
    status: 'ACTIVE',
    primaryRole: 'Country Admin',
    assignedRoles: ['Country Admin', 'Institutional Investor'],
    mfaEnabled: true,
    mfaStatus: 'Enforced',
    kycLevel: 'Level 3',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-11T15:45:00Z',
    joinedDate: 'Jan 2024',
    timezone: 'Asia/Karachi',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2026-08-11T15:45:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01',
    roleHistory: []
  },
  {
    userId: 'USR-PAK-002',
    fullName: 'Fatima Al-Zahra',
    email: 'fatima.wealth@indusfamily.pk',
    phone: '+92 21 888 1122',
    department: 'Family Trust & Wealth Management',
    jobTitle: 'Senior Portfolio Manager',
    organisationId: 'ORG-EMIRATES-FO',
    countryNodeId: 'CN-PAK',
    status: 'ACTIVE',
    primaryRole: 'Institutional Investor',
    assignedRoles: ['Institutional Investor', 'Asset Manager'],
    mfaEnabled: true,
    mfaStatus: 'Enabled',
    kycLevel: 'Level 3',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-10T18:20:00Z',
    joinedDate: 'Feb 2025',
    timezone: 'Asia/Karachi',
    createdAt: '2025-02-14T10:00:00Z',
    updatedAt: '2026-08-10T18:20:00Z',
    createdBy: 'USR-PAK-001',
    updatedBy: 'USR-PAK-001',
    roleHistory: []
  },
  {
    userId: 'USR-TUR-001',
    fullName: 'Emin Yilmaz',
    email: 'emin.yilmaz@istanbultech.tr',
    phone: '+90 532 111 2233',
    department: 'Renewable Infrastructure & Treasury',
    jobTitle: 'VP Infrastructure & Project Sponsor',
    organisationId: 'ORG-BORS-IST',
    countryNodeId: 'CN-TUR',
    status: 'ACTIVE',
    primaryRole: 'Project Sponsor',
    assignedRoles: ['Project Sponsor', 'Treasury Officer'],
    mfaEnabled: true,
    mfaStatus: 'Enforced',
    kycLevel: 'Corporate KYB',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-11T11:10:00Z',
    joinedDate: 'Feb 2025',
    timezone: 'Europe/Istanbul',
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2026-08-11T11:10:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01',
    roleHistory: []
  },
  {
    userId: 'USR-IDN-001',
    fullName: 'Nurul Hidayah',
    email: 'nurul.hidayah@nusacapital.co.id',
    phone: '+62 811 9988 7766',
    department: 'Regulatory Compliance & Risk',
    jobTitle: 'Chief Compliance Officer',
    organisationId: 'ORG-NUSA-DEV',
    countryNodeId: 'CN-IDN',
    status: 'ACTIVE',
    primaryRole: 'Compliance Officer',
    assignedRoles: ['Compliance Officer', 'Risk Officer'],
    mfaEnabled: true,
    mfaStatus: 'Enabled',
    kycLevel: 'Level 3',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-11T09:30:00Z',
    joinedDate: 'Jun 2025',
    timezone: 'Asia/Jakarta',
    createdAt: '2025-06-10T14:00:00Z',
    updatedAt: '2026-08-11T09:30:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01',
    roleHistory: []
  },
  {
    userId: 'USR-IDN-002',
    fullName: 'Budi Santoso',
    email: 'budi.santoso@nusacapital.co.id',
    phone: '+62 812 3344 5566',
    department: 'Port Operations & Logistics',
    jobTitle: 'Senior Marine Asset Manager',
    organisationId: 'ORG-NUSA-DEV',
    countryNodeId: 'CN-IDN',
    status: 'ACTIVE',
    primaryRole: 'Asset Manager',
    assignedRoles: ['Asset Manager', 'Asset Owner'],
    mfaEnabled: true,
    mfaStatus: 'Enabled',
    kycLevel: 'Level 2',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-09T17:10:00Z',
    joinedDate: 'Jul 2025',
    timezone: 'Asia/Jakarta',
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-08-09T17:10:00Z',
    createdBy: 'USR-IDN-001',
    updatedBy: 'USR-IDN-001',
    roleHistory: []
  },
  {
    userId: 'USR-MYS-005',
    fullName: 'Rashid Khan',
    email: 'rashid.audit@albaraka.com.my',
    phone: '+60 19 556 6778',
    department: 'Internal Audit & Shariah Review',
    jobTitle: 'Head of Internal Audit',
    organisationId: 'ORG-ISLAMIC-BANK-MYS',
    countryNodeId: 'CN-MYS',
    status: 'ACTIVE',
    primaryRole: 'Audit Officer',
    assignedRoles: ['Audit Officer', 'Shariah Reviewer'],
    mfaEnabled: true,
    mfaStatus: 'Enforced',
    kycLevel: 'Level 3',
    verified: true,
    profilePhoto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    lastLogin: '2026-08-11T13:20:00Z',
    joinedDate: 'Apr 2024',
    timezone: 'Asia/Kuala_Lumpur',
    createdAt: '2024-04-12T10:00:00Z',
    updatedAt: '2026-08-11T13:20:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01',
    roleHistory: []
  }
];
