import { 
  RevenueTransactionItem, 
  RevenueBillingRecord, 
  SubscriptionRecord, 
  AICreditSaleRecord, 
  PromotionSaleRecord,
  RevenueSummaryMetrics
} from './revenueManagementTypes';

export const INITIAL_REVENUE_METRICS_DATA: RevenueSummaryMetrics = {
  totalRevenueUSD: 312450,
  totalRevenueMYR: 1312290,
  mrrUSD: 44850,
  mrrMYR: 188370,
  arrUSD: 538200,
  arrMYR: 2260440,
  totalPaidMembers: 1680,
  membershipRevenueUSD: 142500,
  aiRevenueUSD: 48900,
  pdpRevenueUSD: 41200,
  featuredListingRevenueUSD: 28650,
  premiumReportRevenueUSD: 16800,
  advertisingRevenueUSD: 21400,
  enterpriseRevenueUSD: 13000,
  revenueGrowthPct: 26.4,
  conversionRatePct: 14.8
};

export const INITIAL_TRANSACTIONS_DATA: RevenueTransactionItem[] = [
  {
    id: 'TXN-2026-901',
    invoiceId: 'INV-2026-901',
    date: '2026-08-12',
    customerName: 'Dato Haji Azman Mansor',
    customerOrg: 'FELDA Technoplant Sdn Bhd',
    customerEmail: 'azman.mansor@felda.gov.my',
    country: 'Malaysia',
    userType: 'Delivery Partner / Project Sponsor',
    category: 'Featured Listing',
    description: 'Featured Project (30 Days) - Smart Palm Oil Mill Modernisation',
    amountMYR: 299,
    amountUSD: 72,
    taxMYR: 17.94,
    netMYR: 281.06,
    paymentGateway: 'Corporate FPX (Maybank Islamic)',
    status: 'Paid',
    membershipTier: 'Enterprise',
    pdpTier: 'Pro PDP',
    promotionBadge: 'Featured'
  },
  {
    id: 'TXN-2026-902',
    invoiceId: 'INV-2026-902',
    date: '2026-08-11',
    customerName: 'Ibrahim Al-Mansoor',
    customerOrg: 'IsDB Private Equity Fund',
    customerEmail: 'i.mansoor@isdb.org',
    country: 'Global',
    userType: 'Institutional Investor',
    category: 'Membership',
    description: 'Wealth Pooling Professional Membership (Annual Subscription)',
    amountMYR: 1188,
    amountUSD: 285,
    taxMYR: 71.28,
    netMYR: 1116.72,
    paymentGateway: 'Sovereign Clearing Node',
    status: 'Paid',
    membershipTier: 'Professional',
    pdpTier: 'None'
  },
  {
    id: 'TXN-2026-903',
    invoiceId: 'INV-2026-903',
    date: '2026-08-10',
    customerName: 'Nurul Huda binti Othman',
    customerOrg: 'MARA Corporation Berhad',
    customerEmail: 'nurul.huda@mara.gov.my',
    country: 'Malaysia',
    userType: 'Delivery Partner / Project Sponsor',
    category: 'Marketplace Advertising',
    description: 'Sponsored Project Spotlight (30 Days) - Halal Logistics Hub',
    amountMYR: 499,
    amountUSD: 120,
    taxMYR: 29.94,
    netMYR: 469.06,
    paymentGateway: 'Corporate Card',
    status: 'Paid',
    membershipTier: 'Professional',
    pdpTier: 'Enterprise PDP',
    promotionBadge: 'Sponsored'
  },
  {
    id: 'TXN-2026-904',
    invoiceId: 'INV-2026-904',
    date: '2026-08-09',
    customerName: 'Prof. Dr. Mehmet Ozkan',
    customerOrg: 'Ziraat Katilim Asset Management',
    customerEmail: 'mehmet.ozkan@ziraatkatilim.com.tr',
    country: 'Turkey',
    userType: 'HNWI Investor',
    category: 'AI Credits',
    description: 'Wealth Pooling AI Utility Credits Pack (1,000,000 Shariah Scans)',
    amountMYR: 399,
    amountUSD: 95,
    taxMYR: 23.94,
    netMYR: 375.06,
    paymentGateway: 'D-8 Wealth Wallet',
    status: 'Paid',
    membershipTier: 'Plus',
    tokensQuantity: 1000000
  },
  {
    id: 'TXN-2026-905',
    invoiceId: 'INV-2026-905',
    date: '2026-08-08',
    customerName: 'Bambang Soedarmono',
    customerOrg: 'PT Bank Muamalat Indonesia Tbk',
    customerEmail: 'bambang.s@muamalatbank.co.id',
    country: 'Indonesia',
    userType: 'Enterprise Member',
    category: 'Enterprise Node',
    description: 'Enterprise Sovereign Node Connection & Data Feed License (Q3)',
    amountMYR: 4500,
    amountUSD: 1080,
    taxMYR: 270.00,
    netMYR: 4230.00,
    paymentGateway: 'Bank Transfer (IsDB RTGS)',
    status: 'Paid',
    membershipTier: 'Enterprise'
  },
  {
    id: 'TXN-2026-906',
    invoiceId: 'INV-2026-906',
    date: '2026-08-07',
    customerName: 'Dr. Zaharuddin Abd Rahman',
    customerOrg: 'Amanie Advisors Sdn Bhd',
    customerEmail: 'zaharuddin@amanieadvisors.com',
    country: 'Malaysia',
    userType: 'Shariah Scholar / Firm',
    category: 'Featured Listing',
    description: 'Promoted Professional Service Practice (30 Days)',
    amountMYR: 199,
    amountUSD: 48,
    taxMYR: 11.94,
    netMYR: 187.06,
    paymentGateway: 'Direct Debit',
    status: 'Paid',
    promotionBadge: 'Promoted'
  },
  {
    id: 'TXN-2026-907',
    invoiceId: 'INV-2026-907',
    date: '2026-08-06',
    customerName: 'Ahmad Faiz Shukri',
    customerOrg: 'Individual Wealth Account',
    customerEmail: 'ahmad.faiz@gmail.com',
    country: 'Malaysia',
    userType: 'Retail Investor',
    category: 'Premium Report',
    description: 'Unlocked: D-8 Sovereign Sukuk & Currency Spread Risk Matrix',
    amountMYR: 99,
    amountUSD: 24,
    taxMYR: 5.94,
    netMYR: 93.06,
    paymentGateway: 'Corporate FPX (Maybank Islamic)',
    status: 'Paid',
    membershipTier: 'Plus'
  },
  {
    id: 'TXN-2026-908',
    invoiceId: 'INV-2026-908',
    date: '2026-08-05',
    customerName: 'Sheikh Tariq Al-Jomaih',
    customerOrg: 'Al-Jomaih Family Office',
    customerEmail: 'tariq@aljomaih-fo.com',
    country: 'Global',
    userType: 'HNWI Investor',
    category: 'PDP Subscription',
    description: 'Pro PDP Plan Monthly Renewal - Agritech Syndication Tier',
    amountMYR: 490,
    amountUSD: 118,
    taxMYR: 29.40,
    netMYR: 460.60,
    paymentGateway: 'Corporate Card',
    status: 'Paid',
    pdpTier: 'Pro PDP'
  },
  {
    id: 'TXN-2026-909',
    invoiceId: 'INV-2026-909',
    date: '2026-08-04',
    customerName: 'Dr. Amina El-Kashif',
    customerOrg: 'Cairo Islamic Venture Partners',
    customerEmail: 'amina@cairoivp.eg',
    country: 'Egypt',
    userType: 'Institutional Investor',
    category: 'AI Credits',
    description: 'Wealth Pooling AI Enterprise Copilot API Quota (500k Tokens)',
    amountMYR: 199,
    amountUSD: 48,
    taxMYR: 11.94,
    netMYR: 187.06,
    paymentGateway: 'D-8 Wealth Wallet',
    status: 'Pending',
    tokensQuantity: 500000
  },
  {
    id: 'TXN-2026-910',
    invoiceId: 'INV-2026-910',
    date: '2026-08-02',
    customerName: 'Tariq Mahmood',
    customerOrg: 'Kuala Lumpur Halal Chambers Syndicate',
    customerEmail: 'tariq.m@klchamber.my',
    country: 'Malaysia',
    userType: 'Delivery Partner / Project Sponsor',
    category: 'Membership',
    description: 'Wealth Pooling Plus Membership (Monthly)',
    amountMYR: 39,
    amountUSD: 9,
    taxMYR: 2.34,
    netMYR: 36.66,
    paymentGateway: 'Corporate Card',
    status: 'Paid',
    membershipTier: 'Plus'
  }
];

export const INITIAL_BILLING_RECORDS_DATA: RevenueBillingRecord[] = [
  {
    id: 'BIL-2026-101',
    invoiceNumber: 'HOW-INV-2026-08-001',
    issueDate: '2026-08-01',
    dueDate: '2026-08-15',
    paidDate: '2026-08-02',
    customerName: 'Dato Haji Azman Mansor',
    customerOrg: 'FELDA Technoplant Sdn Bhd',
    customerEmail: 'azman.mansor@felda.gov.my',
    country: 'Malaysia',
    billingInterval: 'Monthly',
    category: 'Featured Listing',
    lineItems: [
      { description: 'Featured Project 30 Days Placement', quantity: 1, unitPriceMYR: 299, totalMYR: 299 }
    ],
    subtotalMYR: 299,
    taxMYR: 17.94,
    totalMYR: 316.94,
    totalUSD: 76.25,
    status: 'Paid',
    paymentMethod: 'Corporate FPX (Maybank Islamic)',
    notes: 'Paid in full via Bank Negara D-8 interbank clearing channel.'
  },
  {
    id: 'BIL-2026-102',
    invoiceNumber: 'HOW-INV-2026-08-002',
    issueDate: '2026-08-01',
    dueDate: '2026-08-15',
    paidDate: '2026-08-03',
    customerName: 'Ibrahim Al-Mansoor',
    customerOrg: 'IsDB Private Equity Fund',
    customerEmail: 'i.mansoor@isdb.org',
    country: 'Global',
    billingInterval: 'Annual',
    category: 'Membership',
    lineItems: [
      { description: 'Wealth Pooling Professional Tier Annual Access (12 Mos)', quantity: 1, unitPriceMYR: 1188, totalMYR: 1188 }
    ],
    subtotalMYR: 1188,
    taxMYR: 71.28,
    totalMYR: 1259.28,
    totalUSD: 302.71,
    status: 'Paid',
    paymentMethod: 'Sovereign Clearing Node',
    notes: 'Annual upfront license including full AI compliance scan quotas.'
  },
  {
    id: 'BIL-2026-103',
    invoiceNumber: 'HOW-INV-2026-08-003',
    issueDate: '2026-08-05',
    dueDate: '2026-08-20',
    customerName: 'Dr. Amina El-Kashif',
    customerOrg: 'Cairo Islamic Venture Partners',
    customerEmail: 'amina@cairoivp.eg',
    country: 'Egypt',
    billingInterval: 'One-Time',
    category: 'AI Credits',
    lineItems: [
      { description: '500,000 AI Token Execution Credit Quota', quantity: 1, unitPriceMYR: 199, totalMYR: 199 }
    ],
    subtotalMYR: 199,
    taxMYR: 11.94,
    totalMYR: 210.94,
    totalUSD: 50.70,
    status: 'Pending',
    paymentMethod: 'D-8 Wealth Wallet',
    notes: 'Awaiting wallet settlement from Cairo clearing gateway.'
  }
];

export const INITIAL_SUBSCRIPTIONS_DATA: SubscriptionRecord[] = [
  {
    id: 'SUB-2026-01',
    subscriberName: 'Dato Haji Azman Mansor',
    subscriberOrg: 'FELDA Technoplant Sdn Bhd',
    country: 'Malaysia',
    userType: 'Delivery Partner / Project Sponsor',
    type: 'PDP Plan',
    planName: 'Enterprise PDP Tier',
    tier: 'Enterprise PDP',
    monthlyAmountMYR: 990,
    monthlyAmountUSD: 238,
    billingCycle: 'Monthly',
    startDate: '2026-01-15',
    nextBillingDate: '2026-09-15',
    autoRenew: true,
    status: 'Active',
    healthScore: 'Good'
  },
  {
    id: 'SUB-2026-02',
    subscriberName: 'Ibrahim Al-Mansoor',
    subscriberOrg: 'IsDB Private Equity Fund',
    country: 'Global',
    userType: 'Institutional Investor',
    type: 'Membership',
    planName: 'Wealth Pooling Professional Annual',
    tier: 'Professional',
    monthlyAmountMYR: 99,
    monthlyAmountUSD: 24,
    billingCycle: 'Annual',
    startDate: '2026-03-01',
    nextBillingDate: '2027-03-01',
    autoRenew: true,
    status: 'Active',
    healthScore: 'Good'
  },
  {
    id: 'SUB-2026-03',
    subscriberName: 'Bambang Soedarmono',
    subscriberOrg: 'PT Bank Muamalat Indonesia Tbk',
    country: 'Indonesia',
    userType: 'Enterprise Member',
    type: 'Enterprise Node',
    planName: 'D-8 Sovereign Node Partner',
    tier: 'Enterprise',
    monthlyAmountMYR: 1500,
    monthlyAmountUSD: 360,
    billingCycle: 'Monthly',
    startDate: '2026-02-10',
    nextBillingDate: '2026-09-10',
    autoRenew: true,
    status: 'Active',
    healthScore: 'Good'
  },
  {
    id: 'SUB-2026-04',
    subscriberName: 'Nurul Huda binti Othman',
    subscriberOrg: 'MARA Corporation Berhad',
    country: 'Malaysia',
    userType: 'Delivery Partner / Project Sponsor',
    type: 'PDP Plan',
    planName: 'Pro PDP Plan',
    tier: 'Pro PDP',
    monthlyAmountMYR: 490,
    monthlyAmountUSD: 118,
    billingCycle: 'Monthly',
    startDate: '2026-05-20',
    nextBillingDate: '2026-08-20',
    autoRenew: true,
    status: 'Active',
    healthScore: 'Good'
  }
];

export const INITIAL_AI_CREDIT_SALES_DATA: AICreditSaleRecord[] = [
  {
    id: 'AIC-01',
    date: '2026-08-12',
    customerName: 'Prof. Dr. Mehmet Ozkan',
    customerOrg: 'Ziraat Katilim Asset Management',
    country: 'Turkey',
    packageTitle: 'Enterprise 1M Token Package',
    tokenCount: 1000000,
    priceMYR: 399,
    priceUSD: 95,
    paymentMethod: 'D-8 Wealth Wallet',
    usagePurpose: 'Deep AAOIFI Shariah & ESG Portfolio Scans',
    consumedSoFar: 284000
  },
  {
    id: 'AIC-02',
    date: '2026-08-08',
    customerName: 'Dr. Amina El-Kashif',
    customerOrg: 'Cairo Islamic Venture Partners',
    country: 'Egypt',
    packageTitle: 'Growth 500k Token Quota',
    tokenCount: 500000,
    priceMYR: 199,
    priceUSD: 48,
    paymentMethod: 'D-8 Wealth Wallet',
    usagePurpose: 'Cross-Border Sukuk Ijarah Document Analysis',
    consumedSoFar: 92000
  },
  {
    id: 'AIC-03',
    date: '2026-08-02',
    customerName: 'Dato Haji Azman Mansor',
    customerOrg: 'FELDA Technoplant Sdn Bhd',
    country: 'Malaysia',
    packageTitle: 'Starter 250k Token Pack',
    tokenCount: 250000,
    priceMYR: 99,
    priceUSD: 24,
    paymentMethod: 'Corporate FPX',
    usagePurpose: 'Milestone Completion Proof Automated Review',
    consumedSoFar: 180000
  }
];

export const INITIAL_PROMOTION_SALES_DATA: PromotionSaleRecord[] = [
  {
    id: 'PRM-01',
    date: '2026-08-01',
    targetTitle: 'FELDA Smart Palm Oil Mill & Biogas Modernisation',
    sponsorOrg: 'FELDA Technoplant Sdn Bhd',
    country: 'Malaysia',
    packageType: 'Featured 30D',
    durationDays: 30,
    priceMYR: 299,
    priceUSD: 72,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    status: 'ACTIVE',
    views: 3420,
    clicks: 412,
    leads: 38
  },
  {
    id: 'PRM-02',
    date: '2026-08-05',
    targetTitle: 'MARA Halal Food Processing Logistics Hub',
    sponsorOrg: 'MARA Corporation Berhad',
    country: 'Malaysia',
    packageType: 'Sponsored 30D',
    durationDays: 30,
    priceMYR: 499,
    priceUSD: 120,
    startDate: '2026-08-05',
    endDate: '2026-09-04',
    status: 'ACTIVE',
    views: 5240,
    clicks: 680,
    leads: 62
  },
  {
    id: 'PRM-03',
    date: '2026-08-01',
    targetTitle: 'National Cooperative Apex (ANGKASA) Sovereign Sponsor',
    sponsorOrg: 'ANGKASA Malaysia',
    country: 'Malaysia',
    packageType: 'Sponsored Takeover',
    durationDays: 30,
    priceMYR: 999,
    priceUSD: 240,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    status: 'ACTIVE',
    views: 14850,
    clicks: 1620,
    leads: 142
  },
  {
    id: 'PRM-04',
    date: '2026-08-01',
    targetTitle: 'Amanie Shariah & Legal Advisors Directory Placement',
    sponsorOrg: 'Amanie Advisors Sdn Bhd',
    country: 'Malaysia',
    packageType: 'Promoted Practice',
    durationDays: 30,
    priceMYR: 199,
    priceUSD: 48,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    status: 'ACTIVE',
    views: 2840,
    clicks: 310,
    leads: 29
  }
];
