import React, { useMemo, useState } from 'react';
import { CheckCircle2, Download, FileSignature, Info, ShieldAlert, WandSparkles } from 'lucide-react';
import { apiClient, BackendAgreementDraft } from '../../../services/apiClient';

type AgreementType = 'IJARAH' | 'MUSHARAKAH' | 'MUDARABAH' | 'WAKALAH' | 'SUKUK';
type FieldDefinition = { key: string; label: string; required: boolean; suggestion: string; guidance: string; example: string };

const labels: Record<AgreementType, string> = { IJARAH: 'Ijarah Agreement', MUSHARAKAH: 'Musharakah JV Agreement', MUDARABAH: 'Mudarabah Agreement', WAKALAH: 'Wakalah Agreement', SUKUK: 'Sukuk Structure Document' };
const field = (key: string, label: string, suggestion: string, guidance: string, example: string, required = true): FieldDefinition => ({ key, label, suggestion, guidance, example, required });
const fields: Record<AgreementType, FieldDefinition[]> = {
  IJARAH: [field('lessorName', 'Lessor name', 'Use the registered asset owner or SPV name.', 'Identify the legal owner; the lessor must retain ownership or usufruct.', 'Meridian Property SPV Sdn. Bhd.'), field('lesseeName', 'Lessee name', 'Use the operating entity receiving the usufruct.', 'Match the entity name to KYC and constitutional records.', 'Meridian Retail Sdn. Bhd.'), field('assetDescription', 'Asset description', 'Identify the asset, location, title reference, and permitted use.', 'The asset must be identifiable and deliverable.', 'Grade-A retail lot at Lot 12, Kuala Lumpur, title no. PN 12345.'), field('ownershipMaintained', 'Ownership maintained?', 'Yes - ownership remains with the lessor throughout the lease.', 'Ijarah rental is for usufruct and must not disguise an immediate ownership transfer.', 'Yes, ownership remains with the lessor.'), field('rentalAmount', 'Rental amount', 'Set a clearly determinable amount or benchmark-linked formula.', 'State currency, amount, payment dates, and review mechanism.', 'MYR 85,000 per month.'), field('rentalFrequency', 'Rental frequency', 'Monthly or quarterly schedules are common for commercial assets.', 'Payment timing must be certain and linked to the lease term.', 'Monthly in advance on the first business day.'), field('leaseTerm', 'Lease period', 'Commercial property leases commonly use 3-10 year periods.', 'Specify commencement, expiry, renewal options, and early termination.', 'Five years commencing 1 January 2027.')],
  MUSHARAKAH: [field('projectType', 'Project type', 'Property development, investment fund, and operating ventures are common.', 'Describe the activity and confirm it is Shariah-permissible.', 'Property Development'), field('partners', 'Partners', 'List every partner, legal entity, and beneficial ownership role.', 'Distinguish capital partner, managing partner, and investor.', 'Meridian Holdings Sdn. Bhd.; D8 Growth Fund LP.'), field('contributions', 'Capital contributions', 'State each contribution, currency, timing, and cash or asset form.', 'Contributions establish ownership and loss allocation.', 'Sponsor 30% / MYR 3m; investors 70% / MYR 7m.'), field('profitSharing', 'Profit sharing', 'Agree percentages or a distributable-profit formula.', 'Profit may be shared by agreement but must not be a guaranteed return.', 'Sponsor 40%; investors 60% of distributable profit.'), field('lossAllocation', 'Loss allocation according to capital', 'Losses are normally allocated in proportion to capital.', 'Do not guarantee losses contrary to capital contribution.', 'Losses: 30% sponsor / 70% investors.'), field('managementRights', 'Management rights', 'Define reserved matters, authority, voting thresholds, and reporting.', 'Separate management authority from ownership.', 'Managing partner handles operations; sale requires unanimous approval.', false), field('exitMechanism', 'Exit mechanism', 'Buy-out, asset sale, dissolution, and valuation mechanisms are common.', 'Review any promise to repurchase capital at par.', 'Buy-out after year three at an independent valuation.')],
  MUDARABAH: [field('capitalProvider', 'Rabb-ul-mal / capital provider', 'Identify the capital provider and contribution.', 'The capital provider bears commercial loss subject to Mudarib misconduct.', 'D8 Growth Fund LP'), field('manager', 'Mudarib / manager', 'Identify the manager and delegated investment mandate.', 'Define duties, restrictions, reporting, and misconduct events.', 'Meridian Asset Management Sdn. Bhd.'), field('capitalAmount', 'Capital amount', 'State committed capital, currency, drawdowns, and permitted use.', 'Capital and the investment mandate must be identifiable.', 'MYR 10,000,000 in two drawdowns.'), field('profitSharing', 'Profit ratio', 'State the agreed profit-sharing ratio.', 'The Mudarib share must be a percentage of actual profit.', '70% Rabb-ul-mal / 30% Mudarib.'), field('guaranteedReturn', 'Fixed guaranteed return?', 'No fixed or guaranteed return should be stated.', 'A guarantee can invalidate the intended structure and requires review.', 'No fixed guaranteed return; distributions depend on actual profit.'), field('useOfProceeds', 'Use of proceeds', 'Describe permitted assets, sectors, limits, and prohibited activities.', 'Use of proceeds must support monitoring and Shariah screening.', 'Acquisition and lease-up of halal logistics assets.')],
  WAKALAH: [field('principal', 'Principal', 'Identify the investor or asset owner appointing the agent.', 'Use the full legal name and define mandate asset ownership.', 'D8 Investment Company Berhad'), field('agent', 'Agent', 'Identify the manager or service provider acting as Wakil.', 'Define authority limits and required approvals.', 'Meridian Asset Management Sdn. Bhd.'), field('agencyScope', 'Agency scope', 'Set permitted investments, geography, asset class, and limits.', 'The mandate must be defined to avoid governance uncertainty.', 'Manage halal logistics assets in Malaysia within a MYR 20m limit.'), field('agencyFee', 'Agency fee', 'State a fixed or determinable fee and payment timing.', 'The fee must be agreed, disclosed, and separate from incentives.', 'MYR 120,000 per year, paid quarterly.'), field('reporting', 'Reporting and controls', 'Monthly financial and quarterly Shariah reporting are common.', 'Include valuation, conflicts, breach escalation, and audit access.', 'Monthly portfolio report; quarterly Shariah certificate.', false)],
  SUKUK: [field('issuer', 'Issuer', 'Identify issuer, originator, and special purpose vehicle.', 'Map issuer, obligor, trustee, and asset owner roles.', 'Meridian Sukuk Berhad'), field('sukukholders', 'Sukukholders', 'Describe investor class, denomination, and transfer restrictions.', 'Rights depend on the approved structure and asset rights.', 'Institutional investors subscribing for MYR 100,000 denominations.'), field('assetDescription', 'Underlying assets', 'Identify tangible assets, usufruct, or venture underlying the Sukuk.', 'Verify ownership, tradability, and asset eligibility.', 'Lease usufruct in 20 certified logistics warehouses.'), field('capitalAmount', 'Issue size', 'State size, currency, denomination, and settlement date.', 'Match issue size to eligible assets and transaction documents.', 'MYR 250,000,000 issue size.'), field('distributionMechanics', 'Distribution mechanics', 'Define calculation, source, dates, and waterfall.', 'Do not describe distributions as guaranteed interest.', 'Semi-annual distributions from rental proceeds.'), field('redemption', 'Redemption mechanics', 'Define maturity, asset sale, dissolution, and payment waterfall.', 'Review any purchase undertaking or redemption promise.', 'Maturity in seven years after asset sale and dissolution.')],
};

const jurisdictionProfiles: Record<string, { legalSystem: string; authority: string; shariah: string; documents: string[] }> = {
  Malaysia: { legalSystem: 'Common law with statutory Islamic finance framework', authority: 'Bank Negara Malaysia / Securities Commission Malaysia', shariah: 'BNM and SAC SC Shariah Resolutions', documents: ['Islamic Financial Services Act 2013', 'SC Islamic Capital Market guidelines'] },
  'Türkiye': { legalSystem: 'Civil law', authority: 'BRSA and Participation Banks Association advisory bodies', shariah: 'Participation banking standards and adopted AAOIFI references', documents: ['BRSA rules', 'Capital Markets Board participation finance regulations'] },
  Indonesia: { legalSystem: 'Civil law', authority: 'OJK and DSN-MUI', shariah: 'DSN-MUI fatwas and OJK Sharia regulations', documents: ['OJK Islamic finance regulations', 'DSN-MUI fatwas'] },
  Pakistan: { legalSystem: 'Common law with Islamic banking standards', authority: 'State Bank of Pakistan / SECP', shariah: 'SBP Shariah Governance Framework', documents: ['SBP Islamic Banking Guidelines', 'SECP Sukuk regulations'] },
  Bangladesh: { legalSystem: 'Common law', authority: 'Bangladesh Bank Shariah Advisory Committee', shariah: 'Bangladesh Bank Islamic banking guidance', documents: ['Bangladesh Bank Islamic Banking Guidelines', 'BSEC Islamic securities requirements'] },
  Egypt: { legalSystem: 'Civil law', authority: 'Central Bank of Egypt / Financial Regulatory Authority', shariah: 'CBE and FRA Islamic finance and Sukuk guidance', documents: ['CBE banking regulations', 'FRA Sukuk regulations'] },
  Nigeria: { legalSystem: 'Common law with federal financial regulation', authority: 'Central Bank of Nigeria / SEC Nigeria', shariah: 'CBN non-interest banking framework', documents: ['CBN non-interest banking guidelines', 'SEC Nigeria Sukuk rules'] },
  Iran: { legalSystem: 'Civil law with statutory interest-free banking', authority: 'Central Bank of Iran Shariah Council', shariah: 'Interest-Free Banking Act and Council guidance', documents: ['Usury-Free Banking Operations Act', 'CBI banking directives'] },
  Azerbaijan: { legalSystem: 'Civil law', authority: 'Central Bank of Azerbaijan', shariah: 'Central Bank guidance and adopted AAOIFI references', documents: ['Central Bank banking regulations', 'Securities market regulations'] },
};

export const IslamicAgreementWizard: React.FC = () => {
  const [contractType, setContractType] = useState<AgreementType>('MUSHARAKAH');
  const [projectName, setProjectName] = useState('');
  const [jurisdiction, setJurisdiction] = useState('Malaysia');
  const [values, setValues] = useState<Record<string, string>>({});
  const [draft, setDraft] = useState<BackendAgreementDraft | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const currentFields = useMemo(() => fields[contractType], [contractType]);
  const jurisdictionProfile = jurisdictionProfiles[jurisdiction];

  const generate = async () => {
    const missing = currentFields.filter((item) => item.required && !values[item.key]?.trim()).map((item) => item.label);
    if (!projectName.trim() || missing.length) { setError(`Complete required fields: ${['Project name', ...missing.filter((item) => item !== 'Project name')].join(', ')}`); return; }
    setLoading(true); setError('');
    try { setDraft(await apiClient.createAgreementDraft({ contractType, projectName, jurisdiction, wizardData: { ...values, projectName } })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to generate agreement.'); } finally { setLoading(false); }
  };

  return <div className="space-y-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800">
    <div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-emerald-600"><FileSignature className="h-3.5 w-3.5" /> Legal drafting assistant</span><h2 className="mt-2 text-xl font-black text-slate-900 dark:text-white">Islamic Finance Agreement Generation</h2><p className="mt-1 text-xs text-slate-500">Wizard facts are combined with approved clauses, Shariah references, compliance checks, and versioned document output.</p></div>
    <div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-bold">Agreement type<select value={contractType} onChange={(event) => { setContractType(event.target.value as AgreementType); setDraft(null); }} className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-2.5 dark:bg-slate-900">{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-xs font-bold">Project name<input value={projectName} onChange={(event) => setProjectName(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 p-2.5 dark:bg-slate-900" placeholder="e.g. Meridian Residences" /><span className="mt-1 block text-[10px] font-normal text-slate-500">Required · Example: Meridian Residences</span></label><label className="text-xs font-bold">Jurisdiction<select value={jurisdiction} onChange={(event) => setJurisdiction(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-2.5 dark:bg-slate-900">{Object.keys(jurisdictionProfiles).map((country) => <option key={country}>{country}</option>)}</select></label></div>
    {jurisdictionProfile && <div className="grid gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-[11px] text-blue-950 md:grid-cols-2 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-100"><div><strong>Legal system</strong><p>{jurisdictionProfile.legalSystem}</p></div><div><strong>Islamic finance authority</strong><p>{jurisdictionProfile.authority}</p></div><div><strong>Shariah reference</strong><p>{jurisdictionProfile.shariah}</p></div><div><strong>Regulatory documents</strong><p>{jurisdictionProfile.documents.join(' · ')}</p></div></div>}
    <div className="grid gap-3 md:grid-cols-2">{currentFields.map((item) => <div key={item.key} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-3 dark:border-slate-700 dark:bg-slate-900/60"><label className="text-xs font-bold text-slate-700 dark:text-slate-300">{item.label} <span className={item.required ? 'text-rose-600' : 'text-slate-400'}>{item.required ? '(Required)' : '(Optional)'}</span><textarea value={values[item.key] || ''} onChange={(event) => setValues((current) => ({ ...current, [item.key]: event.target.value }))} rows={item.key === 'assetDescription' || item.key === 'partners' ? 3 : 2} placeholder={item.example} className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-2.5 text-xs dark:border-slate-600 dark:bg-slate-900" /></label><div className="mt-2 space-y-1 text-[10px] leading-relaxed"><p className="text-emerald-700 dark:text-emerald-300"><WandSparkles className="mr-1 inline h-3 w-3" /><strong>AI suggestion:</strong> {item.suggestion}</p><p className="text-slate-500 dark:text-slate-400"><Info className="mr-1 inline h-3 w-3" /><strong>Industry guidance:</strong> {item.guidance}</p><p className="text-slate-500 dark:text-slate-400"><strong>Example:</strong> {item.example}</p></div></div>)}</div>
    <button disabled={loading || !projectName.trim()} onClick={() => void generate()} className="inline-flex items-center gap-2 rounded-2xl bg-emerald-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-50"><WandSparkles className="h-4 w-4" />{loading ? 'Assembling agreement...' : 'Generate draft agreement'}</button>
    {error && <p className="rounded-xl bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</p>}
    {draft && <div className="space-y-4 rounded-2xl bg-slate-950 p-4 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-black text-emerald-300">{draft.contract.contractNumber}</p><p className="text-xs text-slate-400">{labels[contractType]} · Draft</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-black ${draft.compliance.status === 'PASS' ? 'bg-emerald-500/20 text-emerald-300' : 'bg-amber-500/20 text-amber-300'}`}><ShieldAlert className="mr-1 inline h-3 w-3" />{draft.compliance.status}</span></div><div className="grid gap-2 md:grid-cols-2">{draft.compliance.checks.map((check) => <div key={check.label} className="rounded-xl bg-white/5 p-2 text-[11px]">{check.pass ? <CheckCircle2 className="mr-1 inline h-3 w-3 text-emerald-400" /> : <ShieldAlert className="mr-1 inline h-3 w-3 text-amber-400" />}{check.label}</div>)}</div><div className="flex flex-wrap gap-2"><button onClick={() => void apiClient.downloadAgreement(draft.contract.id, 'docx')} className="inline-flex items-center gap-1 rounded-xl bg-blue-600 px-3 py-2 text-[11px] font-black"><Download className="h-3.5 w-3.5" /> Word</button><button onClick={() => void apiClient.downloadAgreement(draft.contract.id, 'pdf')} className="inline-flex items-center gap-1 rounded-xl bg-rose-600 px-3 py-2 text-[11px] font-black"><Download className="h-3.5 w-3.5" /> PDF</button></div>{draft.sections.map((section) => <details key={section.number} className="rounded-xl border border-white/10 p-3"><summary className="cursor-pointer text-xs font-black">{section.number}. {section.title}</summary><div className="mt-2 space-y-2 text-[11px] leading-relaxed text-slate-300">{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></details>)}</div>}
  </div>;
};
