import { Organisation } from './organisationTypes';

export const INITIAL_ORGANISATIONS: Organisation[] = [
  {
    organisationId: 'ORG-FELDA-MYS',
    legalName: 'Federal Land Development Authority (FELDA)',
    displayName: 'FELDA Malaysia',
    registrationNumber: 'MY-GOV-FELDA-1956',
    organisationType: 'Government-Linked Company',
    countryNodeId: 'CN-MYS',
    address: 'Menara FELDA, Platinum Park, No 11, Persiaran KLCC, Kuala Lumpur',
    contactEmail: 'corporate@felda.gov.my',
    contactPhone: '+60 3 2191 2191',
    website: 'https://felda.gov.my',
    logoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=200&q=80',
    industry: 'Agriculture & Sustainable Land Development',
    description: 'Federal statutory body transforming rural palm oil, rubber & smart agritech ventures in Malaysia.',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    activeUsersCount: 125,
    activeProjectsCount: 24,
    activeAssetsCount: 42,
    activePoolsCount: 8,
    documents: [
      {
        id: 'DOC-FELDA-001',
        title: 'FELDA Statutory Charter & Act 1956',
        documentType: 'Certificate of Incorporation',
        fileUrl: 'https://example.com/felda_charter.pdf',
        submittedAt: '2024-01-10T10:00:00Z',
        status: 'Approved'
      },
      {
        id: 'DOC-FELDA-002',
        title: 'AAOIFI Shariah Agricultural Sukuk Approval',
        documentType: 'Shariah Approval',
        fileUrl: 'https://example.com/felda_shariah.pdf',
        submittedAt: '2024-01-15T14:20:00Z',
        status: 'Approved'
      }
    ],
    reviewComments: [
      {
        id: 'REV-001',
        reviewerId: 'SYS-ADMIN-01',
        reviewerName: 'Super Admin',
        timestamp: '2024-01-16T09:00:00Z',
        comment: 'Verified statutory government-linked authority profile and Shariah compliance structure.',
        actionTaken: 'Approved'
      }
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01'
  },
  {
    organisationId: 'ORG-D8-GOV',
    legalName: 'Central D-8 Secretariat & Treasury Board',
    displayName: 'D-8 Secretariat',
    registrationNumber: 'GOV-D8-INT-001',
    organisationType: 'Government',
    countryNodeId: 'CN-MYS',
    address: 'Menara D-8 International, Kuala Lumpur, Malaysia',
    contactEmail: 'secretariat@d8.org',
    contactPhone: '+60 3 2188 9000',
    website: 'https://d8.org',
    logoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=200&q=80',
    industry: 'Intergovernmental Economic Cooperation',
    description: 'Central executive body overseeing cross-border economic trade and wealth pooling for Developing-8 nations.',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    activeUsersCount: 42,
    activeProjectsCount: 18,
    activeAssetsCount: 30,
    activePoolsCount: 12,
    documents: [],
    reviewComments: [],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-08-10T15:30:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01'
  },
  {
    organisationId: 'ORG-GULF-CAP',
    legalName: 'Pak Sovereign Capital Holdings & Assets',
    displayName: 'Pak Sovereign Capital',
    registrationNumber: 'SECP-REG-2024-88',
    organisationType: 'Investment Fund',
    countryNodeId: 'CN-PAK',
    address: 'Executive Tower, Blue Area, Islamabad, Pakistan',
    contactEmail: 'corporate@pakcapital.pk',
    contactPhone: '+92 51 300 8800',
    website: 'https://pakcapital.pk',
    logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=200&q=80',
    industry: 'Private Equity & Real Estate Investment',
    description: 'SECP & SBP-regulated Shariah investment manager focused on multi-asset liquidity, agritech, and Sukuk tokenization.',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    activeUsersCount: 14,
    activeProjectsCount: 5,
    activeAssetsCount: 12,
    activePoolsCount: 4,
    documents: [],
    reviewComments: [],
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
    createdBy: 'USR-PAK-001',
    updatedBy: 'USR-PAK-001'
  },
  {
    organisationId: 'ORG-BORS-IST',
    legalName: 'Istanbul Tech Park & Energy Capital A.S.',
    displayName: 'Istanbul Tech Park',
    registrationNumber: 'TUR-IST-88421',
    organisationType: 'Project Sponsor / PDP',
    countryNodeId: 'CN-TUR',
    address: 'Maslak Financial District, Istanbul, Turkey',
    contactEmail: 'projects@istanbultech.tr',
    contactPhone: '+90 212 400 9900',
    website: 'https://istanbultech.tr',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=200&q=80',
    industry: 'Clean Energy & Technology Infrastructure',
    description: 'Energy infrastructure developer managing geothermal and smart grid power projects across Türkiye.',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    activeUsersCount: 8,
    activeProjectsCount: 3,
    activeAssetsCount: 6,
    activePoolsCount: 2,
    documents: [],
    reviewComments: [],
    createdAt: '2024-03-20T00:00:00Z',
    updatedAt: '2026-07-25T09:15:00Z',
    createdBy: 'USR-TUR-003',
    updatedBy: 'USR-TUR-003'
  },
  {
    organisationId: 'ORG-NUSA-DEV',
    legalName: 'PT Nusa Capital Management & Logistics',
    displayName: 'Nusa Capital Indonesia',
    registrationNumber: 'OJK-IDN-99120',
    organisationType: 'Asset Manager',
    countryNodeId: 'CN-IDN',
    address: 'SCBD Tower 8, Jakarta, Indonesia',
    contactEmail: 'admin@nusacapital.co.id',
    contactPhone: '+62 21 570 8821',
    website: 'https://nusacapital.co.id',
    logoUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=200&q=80',
    industry: 'Port Infrastructure & Marine Asset Management',
    description: 'OJK-registered asset manager developing cold chain logistics and port facilities in Surabaya & Jakarta.',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    activeUsersCount: 11,
    activeProjectsCount: 4,
    activeAssetsCount: 8,
    activePoolsCount: 3,
    documents: [],
    reviewComments: [],
    createdAt: '2024-05-10T00:00:00Z',
    updatedAt: '2026-08-05T14:20:00Z',
    createdBy: 'USR-IDN-004',
    updatedBy: 'USR-IDN-004'
  },
  {
    organisationId: 'ORG-ISLAMIC-BANK-MYS',
    legalName: 'Al-Baraka Islamic Financial Corporation',
    displayName: 'Al-Baraka Islamic Financial',
    registrationNumber: 'MY-BNM-BANK-8891',
    organisationType: 'Financial Institution',
    countryNodeId: 'CN-MYS',
    address: 'Kuala Lumpur Financial Center, Malaysia',
    contactEmail: 'institutional@albaraka.com.my',
    contactPhone: '+60 3 2000 8811',
    website: 'https://albaraka.com.my',
    logoUrl: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=200&q=80',
    industry: 'Islamic Banking & Trade Settlement',
    description: 'Licensed Islamic financial institution providing Shariah treasury liquidity, Sukuk underwriting, and trade finance.',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    activeUsersCount: 22,
    activeProjectsCount: 7,
    activeAssetsCount: 15,
    activePoolsCount: 5,
    documents: [],
    reviewComments: [],
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2026-08-07T11:00:00Z',
    createdBy: 'SYS-ADMIN-01',
    updatedBy: 'SYS-ADMIN-01'
  },
  {
    organisationId: 'ORG-EMIRATES-FO',
    legalName: 'Indus Family Wealth & Heritage Trust',
    displayName: 'Indus Family Office',
    registrationNumber: 'SECP-FO-2025-101',
    organisationType: 'Family Office',
    countryNodeId: 'CN-PAK',
    address: 'Clifton Financial Quarter, Karachi, Pakistan',
    contactEmail: 'wealth@indusfamily.pk',
    contactPhone: '+92 21 611 0000',
    website: 'https://indusfamily.pk',
    logoUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=200&q=80',
    industry: 'Multi-Family Wealth & Intergenerational Capital',
    description: 'Private Pakistan family office allocating capital across D-8 infrastructure, halal agribusiness, and Sukuk.',
    status: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    activeUsersCount: 6,
    activeProjectsCount: 2,
    activeAssetsCount: 9,
    activePoolsCount: 2,
    documents: [],
    reviewComments: [],
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2026-08-04T16:00:00Z',
    createdBy: 'USR-PAK-001',
    updatedBy: 'USR-PAK-001'
  }
];
